version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            make install
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: |
            source venv/bin/activate
            make lint
            
  
  build-test-push:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, test and push docker image
          command: |

            docker build -t kibnov/container -t kibnov/container:${CIRCLE_WORKFLOW_ID:0:7} .
            docker run -d --rm --name flaskapp -p 8000:8080 kibnov/container:${CIRCLE_WORKFLOW_ID:0:7}
            sleep 5
            
            
          
  create-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - run:
          name: Set var
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            

  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string

    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/aws-capstone

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Test cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
workflows:
  capstone:
    jobs:
      - lint
      - build-test-push:
          requires:
            - lint
      - create-cluster:
          cluster-name:  devops-capstone-project
          requires:
            - build-test-push

      - create-deployment:
          cluster-name:  devops-capstone-project
          requires:
            - create-cluster

      - aws-eks/update-container-image:
          cluster-name: devops-capstone-project
          container-image-updates: 'aws-capstone=kibnov/aws-capstone:${CIRCLE_WORKFLOW_ID:0:7}'
          get-rollout-status: true
          record: true
          requires:
            - create-deployment
          resource-name:  deployment/aws-capstone

      - test-cluster:
          cluster-name:  devops-capstone-project
          requires:
            - aws-eks/update-container-image
      - aws-eks/delete-cluster:
         cluster-name:  devops-capstone-project
         requires:
           - test-cluster